### ISSUE TITLE
TODO Добавить микрореакции, как подтверждение каждого действия, чтобы  люди понимали что ничего не зависло.

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/api#90]
- [ ] Сделать полосу загрузки более заметной (широкой) в идеале анимация должна быть.
- [ ] Разделить названия кнопок. Сделать "я на месте" только для старта, а "проверить ответ" для заданий с 1-5.
- [ ] При нажатии на кнопку "я на месте" ничего не происходит, если человек не дошел до этого места, ему непонятно. Нужен дружелюбный интерфейс - запилить текст типа "Чтобы начать квест проследуйте на место старта." и кнопка "ок" или "понятно", которая возвращает на пред экран.
- [ ] При нажатии на кнопку "проверить ответ" тоже ничего не происходит. Надо чтобы появлялся текст: "подумайте еще", "возможно поможет подсказка", "вы еще не на нужном месте", короче сделать много таких и по рандому запускать.
- [ ] Оформить страницу 404 в подобном стиле http://www.dejurka.ru/web-design/mistakes-404-3/ с подсказками, типа там обновите страницу, если не помогло обратитесь в поддержку и ссылка, либо форма для заполнения с описанием проблемы.
- [ ] Добавить прогресс бар вверху, чтобы наглядно было видно на каком этапе находится пользователь и сколько осталось. https://s-media-cache-ak0.pinimg.com/236x/79/57/53/79575334fe009e302d0ef527c0b48433.jpg
выбор квеста/старт/1 задание/2 задание/3 задание/4 задание/5 задание/финиш
- [ ] Еще таймер идет, но непонятно для чего и до чего. Добавить "до подсказки осталось" и "до ответа осталось" соответственно.

**Comment by iMega** [comment]
Это больше к UI, тикет перенести в https://github.com/kubikvest/front
